name: Build and Publish

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - azure-pipelines.yml
      - premake5.lua
      - source/**
  pull_request:
    branches:
      - '*'
    paths:
      - azure-pipelines.yml
      - premake5.lua
      - source/**

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    env:
      MODULE_NAME: luapack_internal
      DEPENDENCIES: ${{ github.workspace }}/dependencies
      GARRYSMOD_COMMON: ${{ github.workspace }}/dependencies/garrysmod_common
      GARRYSMOD_COMMON_BRANCH: master
      GARRYSMOD_COMMON_REPOSITORY: https://github.com/danielga/garrysmod_common.git
      PROJECT_GENERATOR_VERSION: 2
      REPOSITORY_DIR: ${{ github.workspace }}
      DISABLE_X86_64_BUILD: false
      BOOTSTRAP_URL: https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.ps1
      BUILD_SCRIPT: ${{ github.workspace }}/dependencies/garrysmod_common/build/build.ps1
      COMPILER_PLATFORM: vs2022
      PROJECT_OS: windows
      PREMAKE5: ${{ github.workspace }}/dependencies/windows/premake-core/premake5.exe
      PREMAKE5_URL: https://github.com/danielga/garrysmod_common/releases/download/premake-build%2F5.0.0-beta2/premake-5.0.0-beta2-windows.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Bootstrap
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString("$env:BOOTSTRAP_URL"))

      - name: Build
        run: powershell.exe -File $env:BUILD_SCRIPT

      - name: Copy files
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/windows
          cp ${{ github.workspace }}/projects/windows/vs2022/*/Release/*.dll ${{ github.workspace }}/artifacts/windows

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ${{ github.workspace }}/artifacts/windows

  linux:
    name: Linux
    runs-on: ubuntu-22.04
    container:
      image: danielga/steamrt-scout:latest
      options: --volume /home
    env:
      MODULE_NAME: luapack_internal
      DEPENDENCIES: ${{ github.workspace }}/dependencies
      GARRYSMOD_COMMON: ${{ github.workspace }}/dependencies/garrysmod_common
      GARRYSMOD_COMMON_BRANCH: master
      GARRYSMOD_COMMON_REPOSITORY: https://github.com/danielga/garrysmod_common.git
      PROJECT_GENERATOR_VERSION: 2
      REPOSITORY_DIR: ${{ github.workspace }}
      DISABLE_X86_64_BUILD: false
      BOOTSTRAP_URL: https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.sh
      BUILD_SCRIPT: ${{ github.workspace }}/dependencies/garrysmod_common/build/build.sh
      COMPILER_PLATFORM: gmake
      PREMAKE5: ${{ github.workspace }}/dependencies/linux/premake-core/premake5
      PROJECT_OS: linux
      PREMAKE5_URL: https://github.com/danielga/garrysmod_common/releases/download/premake-build%2F5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
      CC: gcc-9
      CXX: g++-9
      AR: gcc-ar-9
      NM: gcc-nm-9
      RANLIB: gcc-ranlib-9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Bootstrap
        run: curl -s -L $BOOTSTRAP_URL | bash

      - name: Build
        run: bash $BUILD_SCRIPT

      - name: Copy files
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/linux
          cp ${{ github.workspace }}/projects/linux/gmake/*/Release/*.dll ${{ github.workspace }}/artifacts/linux

      - name: Upload Linux binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ${{ github.workspace }}/artifacts/linux
